repos:
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: flake8
    additional_dependencies: ['darglint', 'pydocstyle<4.0']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.720
  hooks:
  - id: mypy
    args: [--no-strict-optional, --ignore-missing-imports]
#- repo: https://github.com/PyCQA/bandit
#  rev: '1.6.2'
#  hooks:
#  - id: bandit
#    args: [--ini, .bandit, -b, bandit_baseline.json, -q]
- repo: local
  hooks:
  - id: python-bandit-vulnerability-check
    name: Bandit vulnerability check
    entry: bandit
    language: system
#    args: [--ini, .bandit, -b, bandit_baseline.json, -q]
#- repo: https://github.com/jorisroovers/gitlint
#  rev:  v0.12.0
#  hooks:
#  - id: gitlint
